/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package NetflixAppGUI;

/**
 *
 * @author mahmouderradi
 */
import static NetflixAppGUI.NetflixAppFrame.shows;
import static NetflixAppGUI.DisplayShowPanel.model;
import static NetflixAppGUI.DisplayShowPanel.showList;
import Shows.Genre;
import Shows.Language;
import Shows.Quality;
import Shows.Show;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
public class AddShowPanel extends javax.swing.JPanel {
    /**
     * Creates new form AddNetflixPanel
     */
    public AddShowPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        titleTxt = new javax.swing.JTextField();
        numberOfViewsTxt = new javax.swing.JTextField();
        synopsysTxt = new javax.swing.JTextField();
        averageRatingTxt = new javax.swing.JTextField();
        totalWatchTxt = new javax.swing.JTextField();
        genreCombo = new javax.swing.JComboBox<>();
        languageCombo = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        addBtn = new javax.swing.JButton();
        ClearBtn = new javax.swing.JButton();
        qualityCombo = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("Quality");

        jLabel4.setText("Genre");

        jLabel5.setText("Language");

        jLabel6.setText("Number of Views");

        jLabel7.setText("Synopsys");

        jLabel8.setText("Average Rating");

        jLabel9.setText("Total Watch Time");

        jLabel2.setText("Title");

        genreCombo.setModel(new javax.swing.DefaultComboBoxModel<>(Genre.values()));

        languageCombo.setModel(new javax.swing.DefaultComboBoxModel<>(Language.values()));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guis/icons/Load.png"))); // NOI18N
        jLabel1.setText("Enter Show information:");

        addBtn.setFont(new java.awt.Font("Lucida Grande", 1, 11)); // NOI18N
        addBtn.setForeground(new java.awt.Color(0, 0, 204));
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guis/icons/Apply.png"))); // NOI18N
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        ClearBtn.setFont(new java.awt.Font("Lucida Grande", 1, 11)); // NOI18N
        ClearBtn.setForeground(new java.awt.Color(0, 0, 204));
        ClearBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guis/icons/Abort.png"))); // NOI18N
        ClearBtn.setText("Clear");
        ClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBtnActionPerformed(evt);
            }
        });

        qualityCombo.setModel(new javax.swing.DefaultComboBoxModel<>(Quality.values()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(averageRatingTxt)
                            .addComponent(synopsysTxt)
                            .addComponent(numberOfViewsTxt)
                            .addComponent(languageCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(titleTxt)
                            .addComponent(totalWatchTxt)
                            .addComponent(genreCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(qualityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(titleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(qualityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(genreCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(languageCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(numberOfViewsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(synopsysTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(averageRatingTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(totalWatchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(ClearBtn))
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        
        String title = titleTxt.getText();
        if(title.isEmpty()){
            JOptionPane.showMessageDialog(AddShowPanel.this, ""
            + "Please provide a valid title.", "Adding Show", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Quality quality = (Quality) qualityCombo.getSelectedItem();
        Genre genre = (Genre) genreCombo.getSelectedItem();
        Language language = (Language) languageCombo.getSelectedItem();
        
        String numberOfViewsStr = numberOfViewsTxt.getText();
        int numberOfViews;
        try{
            numberOfViews = Integer.parseInt(numberOfViewsStr);
        }catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(AddShowPanel.this, "" + "Please provide a valid Number of Views", ""
                   + "Adding Show", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        String synopsys = synopsysTxt.getText();
        if(synopsys.isEmpty()){
            JOptionPane.showMessageDialog(AddShowPanel.this, ""
            + "Please provide a valid synopsys.", "Adding Show", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String averageRatingStr = averageRatingTxt.getText();
        double averageRating;
        try{
            averageRating = Double.parseDouble(averageRatingStr);
        }catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(AddShowPanel.this, "" + "Please provide a valid Average Rating", ""
                   + "Adding Show", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String totalWatch = totalWatchTxt.getText();
        if(totalWatch.isEmpty()){
            JOptionPane.showMessageDialog(AddShowPanel.this, ""
            + "Please provide a valid total watch time.", "Adding Show", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Show show = new Show(title, quality, genre, language, numberOfViews, synopsys, averageRating, totalWatch);
        shows.addShow(show);
        
        JOptionPane.showMessageDialog(AddShowPanel.this, ""
            + "Show added successfully", "Adding Show", JOptionPane.INFORMATION_MESSAGE);
        
        model.addElement(show);
        showList.setSelectedValue(show, true);
    }//GEN-LAST:event_addBtnActionPerformed

    private void ClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBtnActionPerformed
        // TODO add your handling code here:

        titleTxt.setText("");
        numberOfViewsTxt.setText("");
        synopsysTxt.setText("");
        averageRatingTxt.setText("");
        totalWatchTxt.setText("");
    }//GEN-LAST:event_ClearBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearBtn;
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField averageRatingTxt;
    private javax.swing.JComboBox<Genre> genreCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JComboBox<Language> languageCombo;
    private javax.swing.JTextField numberOfViewsTxt;
    private javax.swing.JComboBox<Quality> qualityCombo;
    private javax.swing.JTextField synopsysTxt;
    private javax.swing.JTextField titleTxt;
    private javax.swing.JTextField totalWatchTxt;
    // End of variables declaration//GEN-END:variables
}
