/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package NetflixAppGUI;

import Shows.Genre;
import Shows.Language;
import Shows.Quality;
import Shows.Show;
import java.util.Set;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author mahmouderradi
 */
public class DisplayShowPanel extends javax.swing.JPanel {
static DefaultListModel<Show> model;
    /**
     * Creates new form DisplayShowPanel
     */
    public DisplayShowPanel() {
        model = new DefaultListModel<>();
        initComponents();
        showList.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        numberOfViewsTxt = new javax.swing.JTextField();
        synopsysTxt = new javax.swing.JTextField();
        averageRatingTxt = new javax.swing.JTextField();
        totalWatchTxt = new javax.swing.JTextField();
        titleTxt = new javax.swing.JTextField();
        qualityTxt = new javax.swing.JTextField();
        genreTxt = new javax.swing.JTextField();
        languageTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        showList = new javax.swing.JList<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();

        setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Number of Views");

        jLabel7.setText("Synopsys");

        jLabel8.setText("Average Rating");

        jLabel9.setText("Total Watch Time");

        jLabel2.setText("Title");

        jLabel3.setText("Quality");

        jLabel4.setText("Genre");

        jLabel5.setText("Language");

        showList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        showList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                showListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(showList);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guis/icons/Bookmark.png"))); // NOI18N
        jLabel1.setText("Display selected show's information");

        jLabel10.setText("Shows:");

        editBtn.setFont(new java.awt.Font("Lucida Grande", 1, 11)); // NOI18N
        editBtn.setForeground(new java.awt.Color(0, 0, 204));
        editBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guis/icons/Diagram.png"))); // NOI18N
        editBtn.setText("Edit");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        deleteBtn.setFont(new java.awt.Font("Lucida Grande", 1, 11)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(0, 0, 204));
        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guis/icons/Bomb.png"))); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(averageRatingTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                .addComponent(synopsysTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(numberOfViewsTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(languageTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(genreTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(qualityTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(titleTxt, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(totalWatchTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(editBtn)
                                .addGap(18, 18, 18)
                                .addComponent(deleteBtn)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel10))
                    .addComponent(titleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(qualityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(genreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(languageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numberOfViewsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(synopsysTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(averageRatingTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalWatchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void showListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_showListValueChanged
        // TODO add your handling code here:
        
        if(evt.getValueIsAdjusting()) return;
        Show show = showList.getSelectedValue();
        if(show == null) return;
        
        titleTxt.setText(show.getTitle());
        qualityTxt.setText(show.getQuality().name());
        genreTxt.setText(show.getGenre().name());
        languageTxt.setText(show.getLang().name());
        numberOfViewsTxt.setText(String.valueOf(show.getNum_views()));
        synopsysTxt.setText(show.getSynopsys());
        averageRatingTxt.setText(String.valueOf(show.getAverage_rating()));
        totalWatchTxt.setText(show.getTotal_watch());
        
        
        
    }//GEN-LAST:event_showListValueChanged

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int selectedIndex = showList.getSelectedIndex();
        model.remove(selectedIndex);
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
        
        String title = titleTxt.getText();
        if(title.isEmpty()){
            JOptionPane.showMessageDialog(DisplayShowPanel.this, ""
            + "Please provide a valid title.", "Editing Show", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String quality = qualityTxt.getText();
        if(!(quality.equalsIgnoreCase(Quality.HD.name()) || quality.equalsIgnoreCase(Quality.ULTRA_HD.name()))){
           JOptionPane.showMessageDialog(DisplayShowPanel.this, ""
            + "Please provide a valid quality.", "Editing Show", JOptionPane.ERROR_MESSAGE);
            return;
         }

        
        String genre = genreTxt.getText();
        if(!(genre.equalsIgnoreCase(Genre.COMEDY.name()) || genre.equalsIgnoreCase(Genre.DRAMA.name()))){
            JOptionPane.showMessageDialog(DisplayShowPanel.this, ""
            + "Please provide a valid genre.", "Editing Show", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String language = languageTxt.getText();
        if(!(language.equalsIgnoreCase(Language.ENGLISH.name()) || language.equalsIgnoreCase(Language.FRENCH.name()) || language.equalsIgnoreCase(Language.SPANISH.name()))){
            JOptionPane.showMessageDialog(DisplayShowPanel.this, ""
            + "Please provide a valid language.", "Editing Show", JOptionPane.ERROR_MESSAGE);
            return;
        }

        
        String numberOfViewsStr = numberOfViewsTxt.getText();
        int numberOfViews;
        try{
            numberOfViews = Integer.parseInt(numberOfViewsStr);
        }catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(DisplayShowPanel.this, "" + "Please provide a valid Number of Views", ""
                   + "Editing Show", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String synopsys = synopsysTxt.getText();
        if(synopsys.isEmpty()){
            JOptionPane.showMessageDialog(DisplayShowPanel.this, ""
            + "Please provide a valid synopsys.", "Editing Show", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String averageRatingStr = averageRatingTxt.getText();
        double averageRating;
        try{
            averageRating = Double.parseDouble(averageRatingStr);
        }catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(DisplayShowPanel.this, "" + "Please provide a valid Average Rating", ""
                   + "Editing Show", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String totalWatch = totalWatchTxt.getText();
        if(totalWatch.isEmpty()){
            JOptionPane.showMessageDialog(DisplayShowPanel.this, ""
            + "Please provide a valid total watch time.", "Editing Show", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Show show = new Show(title, Quality.valueOf(quality), Genre.valueOf(genre), Language.valueOf(language), numberOfViews, synopsys, averageRating, totalWatch);
        int selectedIndex = showList.getSelectedIndex();
        model.set(selectedIndex, show);
        
        JOptionPane.showMessageDialog(DisplayShowPanel.this, ""
            + "Show edited successfully", "Editing Show", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_editBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField averageRatingTxt;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JTextField genreTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField languageTxt;
    private javax.swing.JTextField numberOfViewsTxt;
    private javax.swing.JTextField qualityTxt;
    static javax.swing.JList<Show> showList;
    private javax.swing.JTextField synopsysTxt;
    private javax.swing.JTextField titleTxt;
    private javax.swing.JTextField totalWatchTxt;
    // End of variables declaration//GEN-END:variables
}
